import type { Metadata } from "next";
import { getLocale } from "../dictionaries";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const locale = await getLocale();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={locale} className="h-full antialiased">
      <body>{children}</body>
    </html>
  );
}
